"""empty message

Revision ID: 5398866af95c
Revises: None
Create Date: 2016-05-08 00:33:14.855218

"""

# revision identifiers, used by Alembic.
revision = '5398866af95c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('red_user', sa.Column('profile_picture', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('red_user', 'profile_picture')
    ### end Alembic commands ###
