"""empty message

Revision ID: 6824a27cbc6c
Revises: None
Create Date: 2016-01-14 00:52:33.639504

"""

# revision identifiers, used by Alembic.
revision = '6824a27cbc6c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('red_book', sa.Column('name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('red_book', 'name')
    ### end Alembic commands ###
