"""empty message

Revision ID: 6a305e43ae5b
Revises: fa3b8187cb56
Create Date: 2016-05-13 16:51:46.731795

"""

# revision identifiers, used by Alembic.
revision = '6a305e43ae5b'
down_revision = 'fa3b8187cb56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('loved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'loved')
    ### end Alembic commands ###
