"""empty message

Revision ID: 9d0bf6ab2808
Revises: None
Create Date: 2016-01-13 01:35:17.391053

"""

# revision identifiers, used by Alembic.
revision = '9d0bf6ab2808'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('red_author')
    op.drop_table('red_category')
    op.drop_table('red_book')
    op.drop_table('red_rating')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('red_rating',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], [u'red_book.id'], name=u'red_rating_book_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'red_rating_pkey')
    )
    op.create_table('red_book',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('red_book_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'red_book_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('red_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], [u'red_book.id'], name=u'red_category_book_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'red_category_pkey')
    )
    op.create_table('red_author',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], [u'red_book.id'], name=u'red_author_book_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'red_author_pkey')
    )
    ### end Alembic commands ###
