"""empty message

Revision ID: a50d2bf3f24c
Revises: None
Create Date: 2016-05-15 20:12:15.858683

"""

# revision identifiers, used by Alembic.
revision = 'a50d2bf3f24c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_books', sa.Column('cover_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'cover_url')
    ### end Alembic commands ###
