"""empty message

Revision ID: f357da8f08e7
Revises: None
Create Date: 2016-05-24 14:02:30.988345

"""

# revision identifiers, used by Alembic.
revision = 'f357da8f08e7'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_books')
    op.add_column('red_reading_log', sa.Column('uuid', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'red_reading_log', ['uuid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'red_reading_log', type_='unique')
    op.drop_column('red_reading_log', 'uuid')
    op.create_table('user_books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pages_read', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('loved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('snippet', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cover_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], [u'red_book.id'], name=u'user_books_book_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'red_user.id'], name=u'user_books_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'user_books_pkey')
    )
    ### end Alembic commands ###
