"""empty message

Revision ID: fa3b8187cb56
Revises: 5398866af95c
Create Date: 2016-05-08 00:50:52.834468

"""

# revision identifiers, used by Alembic.
revision = 'fa3b8187cb56'
down_revision = '5398866af95c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('red_user', sa.Column('auth_token_secret', sa.String(), nullable=True))
    op.add_column('red_user', sa.Column('cover_picture', sa.String(), nullable=True))
    op.drop_column('red_user', 'authTokenSecret')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('red_user', sa.Column('authTokenSecret', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('red_user', 'cover_picture')
    op.drop_column('red_user', 'auth_token_secret')
    ### end Alembic commands ###
